### ISSUE TITLE
Setup secure version of the site (Security message)

### ISSUE THREAD

**Issue by andyscoop13** [scoopfoundation13/scoopFoundation#42]
Sometimes when I go on the site I get that warning message, that says Attackers might try to steal their information. (attached). This is perhaps the worst message that could come up, not only does it stop donors from ever givng, it makes the org as a whole look dodgy :( Have you any idea why that happens??
![capture](https://user-images.githubusercontent.com/32106009/31539533-b708f77c-b000-11e7-9a7f-0da10ee36b73.JPG)

**Comment by coakenfold** [comment]
* ssl
* review code for http

**Comment by coakenfold** [comment]
Duplicate of #43
