### ISSUE TITLE
Add pic to SCOOP Story pics

### ISSUE THREAD

**Issue by andyscoop13** [scoopfoundation13/scoopFoundation#7]
Edit the 2nd line on the homepage main pic to say:

We are on a mission to build a kinder world for children

And the pic is a bit blurry, I have a higher version if you think that might help.

**Comment by andyscoop13** [comment]
![20140528_scoop_ _scao__0151_10mb](https://user-images.githubusercontent.com/32106009/30977435-6839765e-a46f-11e7-9be9-b5cd1ebb2f98.jpg)
![20140528_scoop_ _scao__0158_10mb](https://user-images.githubusercontent.com/32106009/30977436-685a045a-a46f-11e7-839d-76bd037f249a.jpg)

**Comment by andyscoop13** [comment]
Pic for SCOOP Gallery:

![cal at airbnb](https://user-images.githubusercontent.com/32106009/30977467-822c7d68-a46f-11e7-8ab2-f8a375f46081.jpg)

**Comment by coakenfold** [comment]
deployed
